@startuml
!include <archimate/Archimate>

title Single Worker Architecture

Group(singleWorkerArch, "Single Worker Architecture") #FFFFFF {
    Application_Component(inferenceApi, "Inference API")
    Application_Service(taskQueue, "Task Queue")
    Technology_Node(singleWorker, "Single Worker\n2GB / 2vCPU")
    Business_Object(musicBucket, "Music Bucket")
    Business_Object(embeddingsDB, "Embeddings DB")
}

Rel_Serving_Up(inferenceApi, musicBucket, "reads audio")
Rel_Serving_Up(inferenceApi, taskQueue, "push task")
Rel_Serving_Up(taskQueue, singleWorker, "pull task")
Rel_Serving_Up(singleWorker, embeddingsDB, "write embeddings")

@enduml

